Collection Page
airswap/airswap-marketplace pull request #30
Opened 2023-01-12 15:55 UTC by filipmanole

- Fetching NFT ids by filtering past events.
- Fetching metadata in chunks while scrolling.

2023-01-12 21:44 UTC, filipmanole commented
Short preview:

![image](https://user-images.githubusercontent.com/19477518/212187584-c2ea1529-16c3-4bd7-a05c-f1e3c68ccb4e.png)

2023-01-16 21:10 UTC, piersss requested changes
How to start your PR:

https://github.com/airswap/airswap-marketplace/blob/main/CONTRIBUTING.md#pr-description

2023-01-16 21:10 UTC, piersss commented on src/components/NFTCard/NFTCard.tsx
> +  <div className="nft-card">
```suggestion
  <div className={`nft-card ${className`}>
```

2023-01-16 21:10 UTC, piersss commented on src/pages/CollectionPage/CollectionPage.tsx
> +  const collectionContract = useContract({ abi: ERC721.abi, address: collectionToken });
contract stuff in the store

2023-01-16 21:10 UTC, piersss commented on src/pages/CollectionPage/CollectionPage.tsx
> +  const fetchCollectionData = async () => {
in the store as a `createAsyncThunk`

2023-01-16 21:10 UTC, piersss commented on src/pages/CollectionPage/CollectionPage.tsx
> +      <div className="nft-list">
nft-list should be in the CollectionWidget

2023-01-17 16:43 UTC, filipmanole commented on src/components/NFTCard/NFTCard.tsx
> +  price: number;
implemented

2023-01-20 10:14 UTC, filipmanole commented
Short video showing the collection page:
https://www.loom.com/share/a023ef4ccc1b4a70a3d405ee20c97bb1

2023-01-24 17:52 UTC, piersss approved these changes
Looks good. Things are working nicely. I added some commits to make it more solid:

1. Your `fetchNFTMetadata` was not setup properly. You only have to make it return a promise and then get the responses in a reducer with the pending, fulfilled, and rejected. So I removed all the collection reducers because they are simply not necessary.

2. You had an `await fetchCallback()` inside the `useInfiniteScroll`. You should keep all async logic inside the store. So I added an `isLoading` to the collection store.

3. I removed `configureCollectionSubscriber`. I understand it's confusing that there's also a `configureBalancesSubscriber` and `configureMetadataSubscriber`. But those subscribers are there because those stores can not be called from a specific `widget`. The collection store is connected to the CollectionWidget, so actions can be called from there.

4. You used a lot of `grid` in your css. It's only necessary when you're using a grid, like the nfts grid. So I left it there only.

5. You had a `onClick` prop on NftCard and used `navigate` for navigation. You should simply use `NavLink` without any listeners.

6. You had classNames like `collection-widget__content__subtitle`, while technically correct it's better to just use `collection-widget__subtitle`.

Things that still need work I have made tickets for:

Infinite scroll and loader needs some work still:
https://github.com/airswap/airswap-marketplace/issues/45

IERC1155 support:
https://github.com/airswap/airswap-marketplace/issues/46

Price of token:
https://github.com/airswap/airswap-marketplace/issues/47

Error handling:
https://github.com/airswap/airswap-marketplace/issues/48

2023-01-24 17:54 UTC, merged